#!/usr/bin/env bash
set -euo pipefail

# Execute the prepared block-level Calibre decks and turn zero reported
# results into a hard, machine-checkable gate.  A successful Calibre process
# alone is not sufficient: each requested summary must be fresh and every
# count on every "TOTAL DRC Results Generated" line must be zero.

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
config_file=${PDE_CALIBRE_CONFIG:-${script_dir}/block_signoff_config.sh}
mode=${1:-all}

case "$mode" in
  drc|antenna|all) ;;
  *)
    echo "usage: $0 {drc|antenna|all}" >&2
    exit 2
    ;;
esac

export PDE_CALIBRE_CONFIG=$config_file
# shellcheck source=block_signoff_config.sh
source "$config_file"
mkdir -p "$PDE_CALIBRE_REPORT_ROOT"

freshness_marker=$(mktemp "${PDE_CALIBRE_REPORT_ROOT}/.pde_calibre_start.XXXXXX")
trap 'rm -f "$freshness_marker"' EXIT

"${script_dir}/run_block_signoff_final.sh" "$mode"

assert_zero_summary() {
  local kind=$1
  local summary=$2

  if [[ ! -s "$summary" ]]; then
    echo "missing or empty $kind summary: $summary" >&2
    return 4
  fi
  if [[ ! "$summary" -nt "$freshness_marker" ]]; then
    echo "$kind summary was not regenerated by this run: $summary" >&2
    return 5
  fi

  if ! awk '
    /^TOTAL DRC Results Generated:/ {
      found = 1
      line = $0
      sub(/^[^:]*:/, "", line)
      gsub(/[^0-9]+/, " ", line)
      count = split(line, value, /[[:space:]]+/)
      numeric = 0
      for (i = 1; i <= count; i++) {
        if (value[i] ~ /^[0-9]+$/) {
          numeric = 1
          if ((value[i] + 0) != 0) {
            nonzero = 1
          }
        }
      }
      if (!numeric) {
        malformed = 1
      }
    }
    END {
      if (!found || malformed) exit 2
      if (nonzero) exit 1
    }
  ' "$summary"; then
    rc=$?
    if [[ $rc -eq 1 ]]; then
      echo "$kind has non-zero Calibre result counts: $summary" >&2
    else
      echo "$kind summary has no parseable TOTAL result count: $summary" >&2
    fi
    return 6
  fi

  echo "PDE_CALIBRE_ZERO_RESULTS_PASS kind=$kind summary=$summary"
}

if [[ "$mode" == drc || "$mode" == all ]]; then
  assert_zero_summary drc "$PDE_DRC_SUMMARY"
fi
if [[ "$mode" == antenna || "$mode" == all ]]; then
  assert_zero_summary antenna "$PDE_ANT_SUMMARY"
fi

echo "PDE_CALIBRE_BLOCK_ZERO_HARD_PASS mode=$mode gds=$PDE_GDS top=$PDE_TOP"
